language: julia

os:
  - linux

julia:
  - 1.0
  - 1.1
  - nightly

jobs:
  allow_failures:
  - julia: nightly

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder());  Codecov.submit(process_folder())'

notifications:
  email: false

addons:
  apt_packages:
    - gfortran
